version: '3'
services:
  app:
    build: .
    depends_on:
      - db
    networks:
      - SET08113-coursework

  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - D:\cyber\Documents\BSc Games Development\Year 2 - Trimester 2\Software Engineering Methods\Coursework RESIT\world-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - SET08113-coursework

networks:
  SET08113-coursework:
    external: true
