version: '3'
services:
  app:
    build: .
    depends_on:
      - db
    networks:
      - SET08113-coursework


  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./world-db:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - SET08113-coursework

networks:
  SET08113-coursework:
    external:
      name: SET08113-coursework

